### ISSUE TITLE
install.sh

### ISSUE THREAD

**Issue by amtrak1007** [km4ack/posit-generator#1]
while running the install script as copied from the repo, I received an error that install.sh could not be found.  after adding the chmod +x permission to the install file it ran as it should.  Linux mint VM on macOS.

**Comment by km4ack** [comment]
there's no harm in running chmod first but it isn't required. the [install command](https://github.com/km4ack/posit-generator?tab=readme-ov-file#install) uses "bash install.sh" which tells the system to use bash to run the install.sh script.
